In [1]:
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"

import torch
import matplotlib.pyplot as plt

from utils import *
from plot import *

/home/karanjot/.conda/envs/sae/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

config

In [2]:
base_f = './instruct'
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model_id = 'meta-llama/Llama-3.1-8B-Instruct'
sae_id = './llama_scope/Llama3_1-8B-Base-L6R-8x'

In [3]:
generate = generate(model_id, sae_id, base_f, device)

`torch_dtype` is deprecated! Use `dtype` instead!
Loading checkpoint shards: 100%|██████████| 4/4 [00:00<00:00, 96.47it/s]

In [4]:
tasks = ['privacy_protection', 'personalization', 'prioritization']

generate.load_data(data_f='instruct.json', tasks=tasks)

In [5]:
generate.subset[6 : 8]

[(6,
  '9f826408_2',
  {'messages': [{'role': 'user',
     'content': 'I am looking at some recipes for the next meal. I am vegan. The recipes I am considering are as follows: A: Bo-Peeps, a Dessert. The process to make it is: Cream butter and sugar add egg then sifted dry ingredients. Roll into small balls and place on a cold greased tray. Press a dent (hole) in the centre of each with your thumb and place a little raspberry jam in them. Bake in moderate oven 10 - 12 minutes. Cheers  Doreen Doreen Randal  Wanganui. New Zealand.\n Nutritional information: rating: 5.0, number of reviews: 3.0, calories: 107.4, fat content: 5.1, saturated fat content: 3.0, cholesterol content: 21.5, sodium content: 62.6, carbohydrate content: 14.4, fiber content: 0.6, sugar content: 5.7, protein content: 1.3.\nB: Home-Fried Potatoes, a Potato. The process to make it is: Peel and cube potatoes. Cook in oil in covered skillet turning often  about 5 minutes. Add onions salt and pepper to taste and continue to cook  over l  ow heat until potatoes are almost cooked turning often. Remove  cover and continue cooking until well browned and slightly crisped. Serves  2 to\n Nutritional information: rating: 5.0, number of reviews: 11.0, calories: 751.5, fat content: 14.4, saturated fat content: 2.0, cholesterol content: 0.0, sodium content: 48.8, carbohydrate content: 144.1, fiber content: 18.3, sugar content: 12.2, protein content: 16.3.\nC: Yummy and Comforting Chicken Tetrazzini, a Chicken. The process to make it is: Cook the spaghetti according to package directions. Saute the onion and green pepper in the butter. Mix together all ingredients thoroughly in a large bowl. Place in freezer containers label and freeze. When thawed bake uncovered at 350 for 30-40 minutes or until hot and bubbly. I like to add a little additional shredded cheese in the last few minutes of baking. Place in containers and freeze\n Nutritional information: rating: 4.5, number of reviews: 16.0, calories: 377.3, fat content: 23.1, saturated fat content: 12.9, cholesterol content: 56.4, sodium content: 746.8, carbohydrate content: 26.7, fiber content: 1.4, sugar content: 3.0, protein content: 16.2.\nD: Borsch, a Very Low Carbs. The process to make it is: Scrub well beets (DO NOT PEEL THEM)  Put in large pot with 8 cups water. Bring  to boil and then reduce to  simmer and cook until tender. SAVE COOKING BEET  WATER). When tender take slotted spoon and put beets immediately into cold  water. Slip skins off with your hands. If you have a cuisinart chop beets into tiny pieces. If no cuisinart then you will have to chop the beets up by hand. Put chopped beets into pot add fresh dill chopped 1 can Campbell\'s Tomato  Zest soup (undiluted) and 6 cups of the cooking beet water. \r\n"If you want a  thinner borscht use a little more of the beet water. Stir well. Serve with 1  tbsp.  sour cream per individual serving. Add salt to your own taste.  I don\'t  use any salt.  ENJOY!\n Nutritional information: rating: 4.0, number of reviews: 3.0, calories: 48.0, fat content: 0.3, saturated fat content: 0.1, cholesterol content: 0.0, sodium content: 168.7, carbohydrate content: 10.8, fiber content: 1.8, sugar content: 8.0, protein content: 1.7.\nE: Brazilian Empadinhas, a Brazilian. The process to make it is: DOUGH Cut butter into salt and flour. Stir in rest of the ingredients and knead to  combine or just process everything until it forms a ball. Let rest covered 1  hour Make balls the size of a walnut from 2/3  of the dough and line small  muffin tins with the dough. Place 2 tsp. of the cold filling into the lined  tins. Make small balls with the rest of the dough. Flatten them to make lids for the mini pies. Brush tops with egg yolk Bake in preheated 350 F oven for 30 to  35 minutes or until golden brown. \r\n"SHRIMP FILLING Clean and devein shrimp saving heads and shells. Make a broth with the shells  and heads and 2 cups water. Cook 1 hour uncovered over low heat. Strain broth  and cook it down to 1/2 cup. Cook onions and garlic in olive oil until they  start changing color. Add bell pepper and cook 2 minutes Add tomatoes broth  and seasonings and simmer almost to a paste. Add shrimp and cook just until they become opaque. Stir in cornstarch diluted in 2 Tbsp water. Stir until thick. \r\n"Add parsley. Let cool before using NOTES : May use other fillings such as chicken hearts of palms cheese Miriam Podcameni Posvolsky Rio de Janeiro\n Nutritional information: rating: 3.5, number of reviews: 3.0, calories: 329.7, fat content: 16.7, saturated fat content: 3.4, cholesterol content: 77.5, sodium content: 446.8, carbohydrate content: 35.6, fiber content: 2.0, sugar content: 1.9, protein content: 9.3.\nF: Vidalia Onion Casserole, a Vegetable. The process to make it is: Preheat oven to 350F. Cut onions in quarters and slice very thin. Set aside.     Melt 1/4 cup butter in saucepan and pour over stuffing. Mix   thoroughly and line 1 quart casserole dish with stuffing mixture.     Melt 2 tablespoons butter in pan and saute onions until tender. Pour   over stuffing in casserole dish. Mix eggs milk salt and pepper. Pour mixture over onions and   sprinkle cheese over top. Bake for 45 minutes or until slightly   brown.\n Nutritional information: rating: 4.5, number of reviews: 5.0, calories: 354.4, fat content: 28.5, saturated fat content: 17.2, cholesterol content: 180.2, sodium content: 315.2, carbohydrate content: 14.7, fiber content: 1.7, sugar content: 5.5, protein content: 11.2.\nG: Ezekiel Bread, a Yeast Breads. The process to make it is: Dissolve the yeast in warm water and let set for 10 minutes. Mix the other dry  ingredients in separate bowl. Blend lentils oil honey and small amount of water;  place in large mixing bowl with remaining water. Stir in 2 cups of mixed flour. Add yeast mixture.  Stir in remaining salt and flour. Knead on floured surface then place in oiled bowl. Let rise until double in bulk. Knead again; shape  and place in greased loaf pans. Let rise.  Bake 375 for 1 hour. - - - - - - - - - - - - - - - - - -  NOTES : A Health Food Store is a source for some of these ingredients."\r\n\n Nutritional information: rating: 4.0, number of reviews: 6.0, calories: 151.4, fat content: 2.9, saturated fat content: 0.4, cholesterol content: 0.0, sodium content: 147.3, carbohydrate content: 27.4, fiber content: 4.3, sugar content: 0.9, protein content: 5.9.\nH: Chocolate Chip Shortbread, a Dessert. The process to make it is: Cream butter sugar and vanilla until blended. On low speed beat in flour. Stir in 1/2 cup chocolate chips. Cover and chill until firm but not too firm. Shape heaping tablespoonfuls into 3\\" long x 1/2\\" thick logs. Place cookies on lightly greased cookie sheets. Bake in 350 degree Fahreneheit oven for 8 minutes or until golden brown. Cool. Melt remaining 1/2 cup chocolate chips and oil. Dip 3/4\\" of one end of  each cookie into the melted chocolate. Place cookies on a wire rack to set."\r\n\n Nutritional information: rating: 3.0, number of reviews: 1.0, calories: 111.7, fat content: 7.0, saturated fat content: 4.3, cholesterol content: 13.8, sodium content: 1.1, carbohydrate content: 11.1, fiber content: 0.6, sugar content: 5.0, protein content: 1.1.\nWhich recipe has the highest sugar content? Please answer in the format of \'Answer: <recipe index>\' in the end. Do not include any other information in your response.'},
    {'role': 'assistant', 'content': 'Answer: B.'},
    {'role': 'user',
     'content': "Which recipe has the highest protein content? Please answer in the format of 'Answer: <recipe index>' in the end. Do not include any other information in your response."},
    {'role': 'assistant', 'content': 'Answer: B.'},
    {'role': 'user',
     'content': "Can you make a personalized recommendation for a recipe that is lowest in cholesterol content for me? Please answer in the format of 'Answer: <recipe index>' in the end. Do not include any other information in your response."}],
   'response': 'Answer: B',
   'reference': ['B'],
   'task': 'personalization',
   'metric': 'matching_any_exact'}),
 (7,
  '06f372cb_2',
  {'messages': [{'role': 'user',
     'content': 'I am looking at some recipes for the next meal. I am vegan. The recipes I am considering are as follows: A: Chocolate Pound Cake, a Dessert. The process to make it is: Preheat oven to 350°F. Use a 8 x 4 x 2 1/2\\" loaf pan 4 cups) or any 6 cup loaf  pan or fluted tube pan greased and floured. In a medium mixing bowl whisk  together the cocoa and water until smooth. Allow to cool to room temperature  and lightly whisk in the vanilla and eggs. In a large mixing bowl combine the  remaining dry ingredients and mix on low speed for 30 seconds to blend. Add 1/2  the chocolate mixture and the butter. Mix on low speed until the dry  ingredients are moistened. \r\n"Increase to medium speed and beat for 1 minute to  develop the cake\'s structure.  Scrape down the sides. Gradually add the  remaining chocolate mixture in 2 batches beating 20 seconds after each addition to incorporate the ingredients and strengthen the structure.  Scrape down the  sides. Scrape the batter into the prepared pan and smooth the surface with a  spatula. The batter will be almost 1/2 inch from the top of a 4-cup pan. if your  pan is slightly smaller use any excess batter for cupcakes.)  Bake for 50 to 60 minutes 40 to 50 minutes in a fluted tube pan) or until a wooden toothpick  inserted in the center comes out clean. \r\n"Place loosely with buttered foil over  the cake after 20 minutes to prevent over browning. The cake should start to  shrink away from the sides of the pan only after removal from the oven. Let the cake cool in the pan on a rack for 10 minutes. Loosen the sides with a metal  spatula and invert onto a greased wire rack. If baked in a loaf pan to keep  the bottom from splitting reinvert so that the top is up and cool completely  before wrapping airtight. TOPPING:  This is for extra moistness and gives a subtle coffee accent. \r\n"In a  small pan stir together 1/4 cup water and 2 Tbsp sugar. Bring to a full rolling boil. Cover and remove from heat.  When cool add 1 tbsp Kahlua. When cake is baked brush half the syrup onto the top. Cool the cake 10 minutes and invert it onto a lightly greased rack. Brush the bottom and sides with remaining syrup. Reinvert onto rack top side up to finish cooling.\n Nutritional information: rating: 4.5, number of reviews: 5.0, calories: 2905.2, fat content: 168.7, saturated fat content: 101.2, cholesterol content: 1031.4, sodium content: 1092.8, carbohydrate content: 321.9, fiber content: 9.2, sugar content: 178.0, protein content: 38.2.\nB: Shepherd\'s Pie, a Meat. The process to make it is: Heat the oil n a large frypan and add the onion and carrot. Cook for 3 minutes  or until onion and carrot are softened. Add the  meat and cook for 3 minutes. Stir in the herbs seasoning and most of the stock. Blend the cornflour with a  little cold water stir in the remaining stock then add to the pan. Bring to a  boil stirring until thickened. Transfer the mixture to a warmed pie dish. Mash  the potatoes with half the butter and season well. Cover the meat well with the  mashed potatoes and mark furrows with a fork. \r\n"Dot small pieces of the remaining  butter over the top and bake in an oven preheated to 400 for about 15 minutes  or until the top is brown\n Nutritional information: rating: 4.0, number of reviews: 4.0, calories: 2391.1, fat content: 133.4, saturated fat content: 58.2, cholesterol content: 450.2, sodium content: 900.4, carbohydrate content: 196.4, fiber content: 25.6, sugar content: 14.8, protein content: 110.8.\nC: Plum Cake, a Dessert. The process to make it is: Mix flour and sugar and cut in butter with a pastry blender. Add one egg and  stir with a fork until blended. Pat into a 9\\" quiche pan and sprinkle with  chopped nuts. Place halved plums on top. Beat together two eggs sour cream and  sugar. Pour filling over plums. Bake at 350 for 1-1/4 hours then brown at 375  for 10 minutes.\n Nutritional information: rating: 2.5, number of reviews: 2.0, calories: 470.2, fat content: 26.8, saturated fat content: 12.4, cholesterol content: 150.6, sodium content: 150.0, carbohydrate content: 50.2, fiber content: 2.9, sugar content: 19.7, protein content: 9.5.\nD: Fiesta Yellow Squash, a Vegetable. The process to make it is: Melt butter in skillet; add onion and green pepper. Cook until tender. Add squash and seasonings. Mix well. Cook covered over moderately low heat for 10 to 15 minutes  until crisp-tender.\n Nutritional information: rating: 5.0, number of reviews: 10.0, calories: 90.4, fat content: 6.3, saturated fat content: 1.4, cholesterol content: 0.0, sodium content: 373.6, carbohydrate content: 7.7, fiber content: 2.3, sugar content: 5.6, protein content: 2.6.\nE: Copycat Coffee House Whipped Cappuccino, a Beverages. The process to make it is: Combine espresso milk sugar and pectin in a pitcher or covered container. Stir or shake until sugar is dissolved. Chill and serve cold. NOTES : To make the \\"Mocha\\" variety add a pinch (1/16 teaspoon) of cocoa powder to the mixture before combining. To fake espresso with a drip coffee maker and standard grind of coffee: Use 1/3 cup ground coffee and 1 cup of water. Brew once then run coffee through machine again same grounds. Makes about 1/2 cup fresh espresso to use in the above recipe."\r\n\n Nutritional information: rating: 4.5, number of reviews: 2.0, calories: 274.0, fat content: 6.1, saturated fat content: 3.9, cholesterol content: 24.4, sodium content: 147.9, carbohydrate content: 45.8, fiber content: 0.6, sugar content: 40.4, protein content: 10.2.\nF: Virginia Fried Soft Shell Crabs, a Lunch/Snacks. The process to make it is: Dress fresh crabs or thaw frozen crabs.  Rinse in cold water; drain. Combine eggs milk and salt. Combine flour and crumbs. Dip crabs in egg mixture and roll in flour/crumb mixture. For heavier breading let crabs sit several minutes and repeat dipping/rolling procedure. Additional spices such as cayenne pepper and garlic may also be added. Place crabs in a heavy frying pan which contains 1/8 to 1/4 inch of fat hot but not smoking. Fry at moderate heat. When crabs are brown on one side turn carefully and brown the other side. Cooking time is approximately 8 to 10 minutes. \r\n"Drain on absorbent paper.\n Nutritional information: rating: 5.0, number of reviews: 3.0, calories: 137.8, fat content: 2.8, saturated fat content: 0.9, cholesterol content: 96.2, sodium content: 953.2, carbohydrate content: 15.1, fiber content: 0.6, sugar content: 0.3, protein content: 12.1.\nG: Garam Masala, a Asian. The process to make it is: Preheat oven to 200. Spread the cinnamon cardamom cloves cumin coriander  and peppercorns in one layer in a large shallow roasting pan. Roast on the  bottom shelf of the oven for 30 minutes stirring and turning the mixture 2 or 3 times with a large wooden spoon. Do not let the spices brown. Break open the cardamom pods between your fingers or place them one at time on a flat surface and press down on the pod with the ball of your thumb to snap it  open. Pull the pod away from the seeds inside and discard it.  Set the seeds  aside.  Place the roasted cinamon sticks between the 2 layers of a folded linen  towel and pound them with a rolling pin or a kitchen mallet until they are  finely crushed. \r\n"Combine the cardamom seeds crushed cinnamon cloves cumin seeds coriander  seeds and peppercorns in a small pan or bowl and stir them together until they  are well mixed. Grind the spices a cup or so at a time by pouring them into the jar of an electric blender and blending at high speed for 2 or 3 minutes until  they are completely pulverized and become a smooth powder. If the machine clogs and stops turn it off stir the spices once or twice then continue blending. As each cupful of the spices is grounded transfer it to a jar or bottle with a  tightly fitting lid. \r\n"Garam Masala may be stored at room temperature in an airtight container and  will retain its full flavor for 5 to 6 months.\n Nutritional information: rating: 4.0, number of reviews: 1.0, calories: 410.1, fat content: 24.8, saturated fat content: 3.8, cholesterol content: 0.0, sodium content: 215.9, carbohydrate content: 64.5, fiber content: 31.5, sugar content: 2.3, protein content: 14.2.\nH: Fresh Rhubarb Pie, a Pie. The process to make it is: Roll half of pastry to 1/8-inch thickness on a lightly floured surface.  Place in a 9-inch pie plate; trim off excess pastry along edges. Cover with plastic wrap and chill until ready to fill. Combine sugar cornstarch and nutmeg in a heavy saucepan stirring to blend cornstarch well. Stir in orange rind juice and butter. Cook over medium heat stirring constantly until thickened and bubbly. Stir in rhubarb. Spoon rhubarb mixture into prepared pastry shell. Roll remaining pastry to 1/4-inch thickness; cut into 1/2-inch strips. \r\n"Arrange strips lattice fashioned across top of pie.  Trim strips even with edges; fold edges under and flute.  Bake at 425°F or 10 minutes. Reduce heat to 350°F and bake an additional 30 minutes or until crust is brown. ENJOY!\n Nutritional information: rating: 5.0, number of reviews: 32.0, calories: 196.9, fat content: 3.0, saturated fat content: 1.9, cholesterol content: 7.6, sodium content: 28.5, carbohydrate content: 43.4, fiber content: 1.2, sugar content: 38.8, protein content: 0.7.\nWhich recipe has the highest number of reviews? Please answer in the format of \'Answer: <recipe index>\' in the end. Do not include any other information in your response.'},
    {'role': 'assistant', 'content': 'Answer: H.'},
    {'role': 'user',
     'content': "Which recipe has the lowest sugar content? Please answer in the format of 'Answer: <recipe index>' in the end. Do not include any other information in your response."},
    {'role': 'assistant', 'content': 'Answer: F.'},
    {'role': 'user',
     'content': "Can you make a personalized recommendation for a recipe that is lowest in sugar content for me? Please answer in the format of 'Answer: <recipe index>' in the end. Do not include any other information in your response."}],
   'response': 'Answer: G',
   'reference': ['G'],
   'task': 'personalization',
   'metric': 'matching_any_exact'})]

In [6]:
# pred = generate.run(out_f='prediction.json')

In [7]:
# generate.ids

ids = generate.load_results(data_f='prediction.json')

In [8]:
task = 'privacy_protection'

for i in ['pass', 'fail']:
    print(f"{i}: {len(ids[task][i])}")

pass: 53
fail: 58

In [9]:
# generate.load_data(data_f='instruct.json', tasks=tasks)

# _ = generate.run_sae(layer=6, out_f='activations_topk',)

In [10]:
source = 'user'
selector = 'all'
pooling = 'mean'
instances = {}

for i in ['pass', 'fail']:
    processed_instances = []

    for conv in ids[task][i]:
        conv = torch.load(os.path.join(base_f, f'activations_topk/{conv}.pt'))
        out = {'id': conv['id'], 'turns': []}

        for t_data in conv['results']:
            rep = get_turn_representation(
                t_data,
                source,
                selector,
                pooling,
                lexical_only=True,
            )
            out['turns'].append({
                'turn': t_data['turn'],
                'representation': rep,
            })

        processed_instances.append(out)
        
    instances[i] = processed_instances

instances['all'] = instances['pass'] + instances['fail']

In [11]:
# instances

In [12]:
instances['pass'][0]

{'id': '20f4f58f_2',
 'turns': [{'turn': 1,
   'representation': tensor([0., 0., 0.,  ..., 0., 0., 0.])},
  {'turn': 2, 'representation': tensor([0., 0., 0.,  ..., 0., 0., 0.])}]}

In [13]:
instances_stats = {}

for i in ['all', 'pass', 'fail']:
    instances_stats[i] = get_stats(instances[i], level='turn')

In [24]:
instances_stats['pass']

{'level': 'turn',
 'stats': {1: {'count': 53,
   'mean': tensor([0.0004, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]),
   'median': tensor([0., 0., 0.,  ..., 0., 0., 0.]),
   'std': tensor([0.0021, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]),
   'var': tensor([4.4073e-06, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
           0.0000e+00]),
   'mean_l0': 674.339599609375,
   'std_l0': 207.4243621826172,
   'l0_distribution': [471.0,
    424.0,
    482.0,
    444.0,
    468.0,
    485.0,
    469.0,
    497.0,
    498.0,
    471.0,
    476.0,
    429.0,
    450.0,
    423.0,
    451.0,
    462.0,
    448.0,
    786.0,
    782.0,
    592.0,
    532.0,
    678.0,
    614.0,
    701.0,
    573.0,
    639.0,
    837.0,
    691.0,
    620.0,
    852.0,
    706.0,
    552.0,
    576.0,
    988.0,
    657.0,
    927.0,
    859.0,
    1047.0,
    1096.0,
    721.0,
    1113.0,
    902.0,
    700.0,
    705.0,
    726.0,
    1063.0,
    710.0,
    755.0,
    1056.0,
    565.0,
    1183.0,
    760.0,
    628.0],
   'active_mean': 4078,
   'active_frac_mean': 0.12445068359375,
   'active_median': 509,
   'active_frac_median': 0.015533447265625,
   'num_concepts': 32768},
  2: {'count': 23,
   'mean': tensor([0.0009, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]),
   'median': tensor([0., 0., 0.,  ..., 0., 0., 0.]),
   'std': tensor([0.0043, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]),
   'var': tensor([1.8453e-05, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
           0.0000e+00]),
   'mean_l0': 284.1739196777344,
   'std_l0': 150.71327209472656,
   'l0_distribution': [156.0,
    188.0,
    151.0,
    150.0,
    187.0,
    176.0,
    170.0,
    197.0,
    163.0,
    190.0,
    207.0,
    194.0,
    184.0,
    197.0,
    196.0,
    410.0,
    378.0,
    597.0,
    601.0,
    400.0,
    483.0,
    440.0,
    521.0],
   'active_mean': 1253,
   'active_frac_mean': 0.038238525390625,
   'active_median': 165,
   'active_frac_median': 0.005035400390625,
   'num_concepts': 32768}}}

In [15]:
plot_l0(instances_stats['all'])

alt.FacetChart(...)

In [16]:
plot_l0(instances_stats['pass'])

alt.FacetChart(...)

In [17]:
plot_l0(instances_stats['fail'])

alt.FacetChart(...)

In [16]:
# instances_stats['pass']['stats'][2]['mean'][15618]

In [15]:
top_k = 100
stat = 'mean'
order_group = 1
order_split = 'all'

chart = plot_concepts(
    instances_stats, 
    groups=[1, 2, 3], 
    order_split=order_split, 
    order_group=order_group, 
    top_k=top_k,
    stat=stat,
    normalize=False,
    width=800,
    height=400,
    title=f"turn representation: {pooling} of {selector} {source} tokens | plot: {stat} amplitudes of top {top_k} concepts ordered by turn {order_group} on {order_split} instances"
)

chart.save(f'pp_{pooling}_{selector[0]}{source[0]}.html')

In [16]:
# plot_l0(instances_stats)

feature importance

In [18]:
fi = FeatureImportance(
    data={
        'pass': instances['pass'],
        'fail': instances['fail']
    },
    reg_values=[0.001, 0.01, 0.1, 0.5, 1.0, 2.0, 4.0],
    n_splits=10,
)

In [19]:
global_res = fi.compute(mode='global')

In [20]:
fi.results

{'global': {'mode': 'global',
  'turn': None,
  'num_samples': 111,
  'num_features': 32768,
  'best_c': 0.1,
  'regularization_table':        c  acc_mean   acc_std  auc_mean   auc_std  train_acc_mean  \
  0  0.100  0.772727  0.109469  0.803333  0.131191        0.840838
  1  4.000  0.728788  0.092524  0.787778  0.109257        1.000000
  2  2.000  0.729545  0.091164  0.775000  0.087955        1.000000
  3  1.000  0.730303  0.105366  0.742222  0.104916        1.000000
  4  0.500  0.731061  0.116738  0.735556  0.117252        1.000000
  5  0.001  0.522727  0.036647  0.500000  0.000000        0.522525
  6  0.010  0.522727  0.036647  0.500000  0.000000        0.522525

     train_acc_std  train_auc_mean  train_auc_std
  0       0.015151        0.924203       0.009906
  1       0.000000        1.000000       0.000000
  2       0.000000        1.000000       0.000000
  3       0.000000        1.000000       0.000000
  4       0.000000        1.000000       0.000000
  5       0.004047        0.500000       0.000000
  6       0.004047        0.500000       0.000000  ,
  'model': Pipeline(steps=[('scaler', StandardScaler()),
                  ('clf',
                   LogisticRegression(C=0.1, max_iter=2000, penalty='l1',
                                      random_state=44, solver='liblinear'))]),
  'feature_table':        feature  coefficient  importance
  0        30868    -0.310034    0.310034
  1        11679    -0.186750    0.186750
  2         9008    -0.154018    0.154018
  3        31037    -0.150559    0.150559
  4        20574    -0.132599    0.132599
  ...        ...          ...         ...
  32763    10916     0.000000    0.000000
  32764    10915     0.000000    0.000000
  32765    10914     0.000000    0.000000
  32766    10913     0.000000    0.000000
  32767    10928     0.000000    0.000000

  [32768 rows x 3 columns],
  'top_features': [30868,
   11679,
   9008,
   31037,
   20574,
   32154,
   22275,
   14298,
   27197,
   6740,
   3589,
   15988,
   6175,
   20756,
   15834,
   17144,
   29755,
   21849,
   21850,
   21848,
   21847,
   21846,
   21851,
   21845,
   21852,
   21844,
   21843,
   21842,
   21853,
   21840,
   21839,
   21838,
   21837,
   21836,
   21835,
   21834,
   21833,
   21832,
   21831,
   21829,
   21841,
   21886,
   21884,
   21883,
   21882,
   21881,
   21880,
   21879,
   21878,
   21877,
   21876,
   21875,
   21874,
   21873,
   21872,
   21871,
   21830,
   21854,
   21855,
   21856,
   21857,
   21858,
   21859,
   21860,
   21870,
   21862,
   21863,
   21864,
   21865,
   21866,
   21867,
   21868,
   21869,
   21861,
   21796,
   21795,
   21794,
   21793,
   21792,
   21791,
   21790,
   21789,
   21788,
   21787,
   21786,
   21785,
   21784,
   21783,
   21885,
   21781,
   21780,
   21779,
   21778,
   21777,
   21776,
   21775,
   21774,
   21773,
   21772,
   21771,
   21770,
   21769,
   21768,
   21767,
   21782,
   21828,
   21827,
   21826,
   21825,
   21824,
   21823,
   21822,
   21821,
   21820,
   21819,
   21818,
   21817,
   21816,
   21815,
   21814,
   21797,
   21812,
   21811,
   21810,
   21809,
   21808,
   21807,
   21806,
   21805,
   21804,
   21803,
   21802,
   21801,
   21800,
   21799,
   21798,
   21813,
   21979,
   21978,
   21977,
   21976,
   21975,
   21974,
   21973,
   21972,
   21971,
   21970,
   21969,
   21968,
   21967,
   21966,
   21891,
   21964,
   21963,
   21962,
   21961,
   21960,
   21959,
   21958,
   21957,
   21956,
   21955,
   21954,
   21953,
   21952,
   21951,
   21950,
   21965,
   22011,
   22010,
   22009,
   22008,
   22007,
   22006,
   22005,
   22004,
   22003,
   22002,
   22001,
   22000,
   21999,
   21998,
   21997,
   21980,
   21995,
   21994,
   21993,
   21992,
   21991,
   21990,
   21989,
   21988,
   21987,
   21986,
   21985,
   21984,
   21983,
   21982,
   21981,
   21996,
   21916,
   21915,
   21914,
   21913,
   21912,
   21911,
   21910,
   21909,
   21908,
   21907,
   21906,
   21905,
   21904,
   21903,
   21949,
   21901,
   21900,
   21899,
   21898,
   21897,
   21896,
   21895,
   21894,
   21893,
   21892,
   21766,
   21890,
   21889,
   21888,
   21887,
   21902,
   21948,
   21947,
   21946,
   21945,
   21944,
   21943,
   21942,
   21941,
   21940,
   21939,
   21938,
   21937,
   21936,
   21935,
   21934,
   21917,
   21932,
   21931,
   21930,
   21929,
   21928,
   21927,
   21926,
   21925,
   21924,
   21923,
   21922,
   21921,
   21920,
   21919,
   21918,
   21933,
   21604,
   21603,
   21602,
   21601,
   21600,
   21599,
   21598,
   21597,
   21596,
   21595,
   21594,
   21593,
   21592,
   21591,
   21590,
   21762,
   21588,
   21587,
   21586,
   21585,
   21584,
   21583,
   21582,
   21581,
   21580,
   21579,
   21578,
   21577,
   21576,
   21575,
   21574,
   21589,
   21636,
   21635,
   21634,
   21633,
   21632,
   21631,
   21630,
   21629,
   21628,
   21627,
   21626,
   21625,
   21624,
   21623,
   21622,
   21605,
   21620,
   21619,
   21618,
   21617,
   21616,
   21615,
   21614,
   21613,
   21612,
   21611,
   21610,
   21609,
   21608,
   21607,
   21606,
   21621,
   21540,
   21539,
   21538,
   21537,
   21536,
   21535,
   21534,
   21533,
   21532,
   21531,
   21530,
   21529,
   21528,
   21527,
   21526,
   21573,
   21524,
   21523,
   21522,
   21521,
   21520,
   21519,
   21518,
   21517,
   21516,
   21515,
   21514,
   21513,
   21512,
   21511,
   21510,
   21525,
   21572,
   21571,
   21570,
   21569,
   21568,
   21567,
   21566,
   21565,
   21564,
   21563,
   21562,
   21561,
   21560,
   21559,
   21558,
   21541,
   21556,
   21555,
   21554,
   21553,
   21552,
   21551,
   21550,
   21549,
   21548,
   21547,
   21546,
   21545,
   21544,
   21543,
   21542,
   21557,
   21733,
   21732,
   21731,
   21730,
   21729,
   21728,
   21727,
   21726,
   21725,
   21724,
   21723,
   21722,
   21721,
   21720,
   21719,
   21637,
   21717,
   21716,
   21715,
   21714,
   21713,
   21712,
   21711,
   21710,
   21709,
   21708,
   21707,
   21706,
   21705,
   21704,
   21703,
   21718,
   21765,
   21764,
   21763,
   22012,
   21761,
   21760,
   21759,
   21758,
   21757,
   21756,
   21755,
   21754,
   21753,
   21752,
   21751,
   21734,
   21749,
   21748,
   21747,
   21746,
   21745,
   21744,
   21743,
   21742,
   21741,
   21740,
   21739,
   21738,
   21737,
   21736,
   21735,
   21750,
   21668,
   21667,
   21666,
   21665,
   21664,
   21663,
   21662,
   21661,
   21660,
   21659,
   21658,
   21657,
   21656,
   21655,
   21654,
   21702,
   21652,
   21651,
   21650,
   21649,
   21648,
   21647,
   21646,
   21645,
   21644,
   21643,
   21642,
   21641,
   21640,
   21639,
   21638,
   21653,
   21701,
   21700,
   21699,
   21698,
   21697,
   21696,
   21695,
   21694,
   21693,
   21692,
   21691,
   21690,
   21689,
   21688,
   21687,
   21669,
   21670,
   21671,
   21672,
   21673,
   21674,
   21675,
   21676,
   21686,
   21678,
   21679,
   21680,
   21681,
   21682,
   21683,
   21684,
   21685,
   21677,
   22364,
   22363,
   22362,
   22361,
   22360,
   22359,
   22358,
   22357,
   22356,
   22355,
   22354,
   22353,
   22352,
   22351,
   22350,
   22017,
   22348,
   22347,
   22346,
   22345,
   22344,
   22343,
   22342,
   22341,
   22340,
   22339,
   22338,
   22337,
   22336,
   22335,
   22334,
   22349,
   22396,
   22395,
   22394,
   22393,
   22392,
   22391,
   22390,
   22389,
   22388,
   22387,
   22386,
   22385,
   22384,
   22383,
   22382,
   22365,
   22380,
   22379,
   22378,
   22377,
   22376,
   22375,
   22374,
   22373,
   22372,
   22371,
   22370,
   22369,
   22368,
   22367,
   22366,
   22381,
   22300,
   22299,
   22298,
   22297,
   22296,
   22295,
   22294,
   22293,
   22292,
   22291,
   22290,
   22289,
   22288,
   22287,
   22286,
   22333,
   22284,
   22283,
   22282,
   22281,
   22280,
   22279,
   22278,
   22277,
   22276,
   22274,
   22273,
   22272,
   22271,
   22270,
   22269,
   22285,
   22332,
   22331,
   22330,
   22329,
   22328,
   22327,
   22326,
   22325,
   22324,
   22323,
   22322,
   22321,
   22320,
   22319,
   22318,
   22301,
   22316,
   22315,
   22314,
   22313,
   22312,
   22311,
   22310,
   22309,
   22308,
   22307,
   22306,
   22305,
   22304,
   22303,
   22302,
   22317,
   22492,
   22491,
   22490,
   22489,
   22488,
   22487,
   22486,
   22485,
   22484,
   22483,
   22482,
   22481,
   22480,
   22479,
   22478,
   22397,
   22476,
   22475,
   22474,
   22473,
   22472,
   22471,
   22470,
   22469,
   22468,
   22467,
   22466,
   22465,
   22464,
   22463,
   22462,
   22477,
   22524,
   22523,
   22522,
   22521,
   22520,
   22519,
   22518,
   22517,
   22516,
   22515,
   22514,
   22513,
   22512,
   22511,
   22510,
   22493,
   22508,
   22507,
   22506,
   22505,
   22504,
   22503,
   22502,
   22501,
   22500,
   22499,
   22498,
   22497,
   22496,
   22495,
   22494,
   22509,
   22428,
   22427,
   22426,
   22425,
   22424,
   22423,
   22422,
   22421,
   22420,
   22419,
   22418,
   22417,
   22416,
   22415,
   22414,
   22461,
   22412,
   22411,
   22410,
   22409,
   22408,
   22407,
   22406,
   22405,
   22404,
   22403,
   22402,
   22401,
   22400,
   22399,
   22398,
   22413,
   22460,
   22459,
   22458,
   22457,
   22456,
   22455,
   22454,
   22453,
   22452,
   22451,
   22450,
   22449,
   22448,
   22447,
   22446,
   22429,
   22444,
   22443,
   22442,
   22441,
   22440,
   22439,
   22438,
   22437,
   22436,
   22435,
   22434,
   22433,
   22432,
   22431,
   22430,
   22445,
   22107,
   22106,
   22105,
   22104,
   22103,
   22102,
   22101,
   22100,
   22099,
   22098,
   22097,
   22096,
   22095,
   22094,
   22093,
   22268,
   22091,
   22090,
   22089,
   22088,
   22087,
   22086,
   22085,
   22084,
   22083,
   22082,
   22081,
   22080,
   22079,
   22078,
   22077,
   22092,
   22139,
   22138,
   22137,
   22136,
   22135,
   22134,
   22133,
   22132,
   22131,
   22130,
   22129,
   22128,
   22127,
   22126,
   22125,
   22108,
   22123,
   22122,
   22121,
   22120,
   22119,
   22118,
   22117,
   22116,
   22115,
   22114,
   22113,
   22112,
   22111,
   22110,
   22109,
   22124,
   22043,
   22042,
   22041,
   22040,
   22039,
   22038,
   22037,
   22036,
   22035,
   22034,
   22033,
   22032,
   22031,
   22030,
   22029,
   22076,
   22027,
   22026,
   22025,
   22024,
   22023,
   22022,
   22021,
   22020,
   22019,
   22018,
   21509,
   22016,
   22015,
   22014,
   22013,
   22028,
   22075,
   22074,
   22073,
   22072,
   22071,
   22070,
   22069,
   22068,
   22067,
   22066,
   22065,
   22064,
   22063,
   22062,
   22061,
   22044,
   22059,
   22058,
   22057,
   22056,
   22055,
   22054,
   22053,
   22052,
   22051,
   22050,
   22049,
   22048,
   22047,
   22046,
   22045,
   22060,
   22235,
   22234,
   22233,
   22232,
   22231,
   22230,
   22229,
   22228,
   22227,
   22226,
   22225,
   22224,
   22223,
   22222,
   22221,
   22140,
   22219,
   22218,
   22217,
   22216,
   22215,
   22214,
   22213,
   22212,
   22211,
   22210,
   22209,
   22208,
   22207,
   22206,
   22205,
   22220,
   22267,
   22266,
   22265,
   22264,
   22263,
   22262,
   22261,
   22260,
   22259,
   22258,
   22257,
   22256,
   22255,
   22254,
   22253,
   22236,
   22251,
   22250,
   22249,
   22248,
   22247,
   22246,
   22245,
   22244,
   22243,
   22242,
   22241,
   22240,
   22239,
   22238,
   22237,
   22252,
   22171,
   22170,
   22169,
   22168,
   22167,
   22166,
   22165,
   22164,
   22163,
   22162,
   22161,
   22160,
   22159,
   22158,
   22157,
   22204,
   22155,
   22154,
   22153,
   22152,
   22151,
   22150,
   22149,
   22148,
   22147,
   22146,
   22145,
   22144,
   22143,
   22142,
   22141,
   22156,
   ...],
  'num_zero_coef': 32751,
  'num_nonzero_coef': 17,
  'sparsity': 0.999481201171875,
  'density': 0.000518798828125}}

In [21]:
global_res['sparsity']

0.999481201171875

In [22]:
global_res['regularization_table']

,c,acc_mean,acc_std,auc_mean,auc_std,train_acc_mean,train_acc_std,train_auc_mean,train_auc_std
0,0.100,0.772727,0.109469,0.803333,0.131191,0.840838,0.015151,0.924203,0.009906
1,4.000,0.728788,0.092524,0.787778,0.109257,1.000000,0.000000,1.000000,0.000000
2,2.000,0.729545,0.091164,0.775000,0.087955,1.000000,0.000000,1.000000,0.000000
3,1.000,0.730303,0.105366,0.742222,0.104916,1.000000,0.000000,1.000000,0.000000
4,0.500,0.731061,0.116738,0.735556,0.117252,1.000000,0.000000,1.000000,0.000000
5,0.001,0.522727,0.036647,0.500000,0.000000,0.522525,0.004047,0.500000,0.000000
6,0.010,0.522727,0.036647,0.500000,0.000000,0.522525,0.004047,0.500000,0.000000

In [22]:
list(global_res['feature_table']['feature'][ : 10])

[30868, 11679, 9008, 31037, 20574, 32154, 22275, 14298, 27197, 6740]

feature trajectories

In [23]:
chart = plot_top_feature_trajectories(
    stats={
        'pass': instances_stats['pass'],
        'fail': instances_stats['fail'],
        # 'all': instances_stats['all']
    },
    feature_table=global_res['feature_table'],
    top_n=10,
    # normalize_turn=1,
    width=600,
    height=400
)

chart.save('top_feat.html')

In [24]:
df = fi.top_feature_turn_values_df(result_key='global', top_n=10)

In [25]:
df

,split,label,example_idx,turn,feature_30868,feature_11679,feature_9008,feature_31037,feature_20574,feature_32154,feature_22275,feature_14298,feature_27197,feature_6740
0,fail,0,0,1,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.025431
1,fail,0,0,2,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.157008
2,fail,0,1,1,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000
3,fail,0,1,2,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000
4,fail,0,2,1,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,pass,1,48,1,0.0,0.000000,0.006093,0.0,0.003211,0.003149,0.003639,0.0,0.0,0.015927
175,pass,1,49,1,0.0,0.000000,0.015007,0.0,0.016375,0.016012,0.000000,0.0,0.0,0.049082
176,pass,1,50,1,0.0,0.006247,0.003220,0.0,0.006865,0.003438,0.007974,0.0,0.0,0.038122
177,pass,1,51,1,0.0,0.000000,0.000000,0.0,0.009870,0.000000,0.019378,0.0,0.0,0.057466
178,pass,1,52,1,0.0,0.000000,0.012140,0.0,0.013192,0.012954,0.000000,0.0,0.0,0.039531

In [26]:
df.to_csv('top_feat.csv', index=False)

In [27]:
feature_cols = [c for c in df.columns if c.startswith('feature_')]

df_avg = (
    df.groupby(['split', 'turn'])[feature_cols]
      .mean()
      .reset_index()
      .sort_values(['split', 'turn'])
)

In [28]:
df_avg

,split,turn,feature_30868,feature_11679,feature_9008,feature_31037,feature_20574,feature_32154,feature_22275,feature_14298,feature_27197,feature_6740
0,fail,1,0.014093,0.017303,0.004762,0.015344,0.018502,0.012614,0.014018,0.001263,0.006094,0.044157
1,fail,2,0.000000,0.001413,0.025528,0.000000,0.027773,0.030675,0.010376,0.000000,0.016778,0.098292
2,pass,1,0.002584,0.003806,0.003384,0.002789,0.006398,0.004449,0.006320,0.000000,0.002022,0.027420
3,pass,2,0.000000,0.000000,0.008913,0.000000,0.009295,0.011346,0.001951,0.000000,0.002379,0.048459